added starship

diff --git a/bash_tools b/bash_tools
--- a/bash_tools
+++ b/bash_tools
@@ -10,6 +10,11 @@ export DESKTOPWINSL='/mnt/c/Users/Gonçalo Sousa/'
 export HISTCONTROL='ignoredups'
 export HISTSIZE=5000
 export HISTFILESIZE=5000
+export LANG=en_US.UTF-8
+export LC_ALL=en_US.UTF-8
+export ANSIBLE_CONFIG="$HOME/.config/ansible/config.ini"
+export ANSIBLE_INVENTORY="$HOME/.config/ansible/inventory.yaml"
+
 
 #Color Man pages
 export LESS_TERMCAP_mb=$'\e[1;32m'
@@ -20,23 +25,14 @@ export LESS_TERMCAP_so=$'\e[01;33m'
 export LESS_TERMCAP_ue=$'\e[0m'
 export LESS_TERMCAP_us=$'\e[1;4;31m'
 
+
+
 MAGENTA="\e[35m"
 YELLOW="\e[33m"
 BLUE="\e[34m"
 GREEN="\e[32m"
 RESET="\e[0m"
 ORANGE="\e[38;5;214m"
-PS1_COLOR_RESET="\[\033[0m\]"
-PS1_COLOR_BOLD="\[\033[1m\]"
-PS1_COLOR_FOREGROUND="\[\033[1;97m\]" # White (Foreground)
-PS1_COLOR_COMMENT="\[\033[1;94m\]"    # Comment (Muted Blue)
-PS1_COLOR_CYAN="\[\033[1;96m\]"
-PS1_COLOR_GREEN="\[\033[1;92m\]"
-PS1_COLOR_ORANGE="\[\033[1;33m\]"
-PS1_COLOR_PINK="\[\033[1;95m\]"
-PS1_COLOR_PURPLE="\[\033[1;35m\]"
-PS1_COLOR_RED="\[\033[1;91m\]"
-PS1_COLOR_YELLOW="\[\033[1;93m\]"
 
 # Custom Alias
 alias ll='ls -la'
@@ -65,8 +61,9 @@ alias gdir='cd $HOME/git'
 alias ldir='cd $HOME/lab'
 alias ddir='cd $HOME/dotfiles'
 alias svim='sudoedit'
+alias v='vim'
 
-# Git Aliases
+# Git Aliases and functions
 alias nb='git checkout -b'
 alias gall='git add -A'
 alias gst='git status'
@@ -86,6 +83,63 @@ alias gp='git push origin'
 alias gst='git status'
 alias gu='git pull' # gu = git update
 alias gs='git switch'
+
+function lazygit() {
+    if [ -z "$1" ]; then
+        echo "Error: Commit message is required."
+        echo "Usage: lazygit '<commit_message>' <branch_name>"
+        return 1
+    fi
+
+    if [ -z "$2" ]; then
+        echo "Error: Branch name is required"
+        echo "Usage: lazygit '<commit_message>' <branch_name>"
+        return 1
+    fi
+
+    git add -A
+    git commit -m "$1"
+    git push -u origin "$2"
+}
+
+gdst() {
+    found_repo=false
+    for dir in */; do
+        echo -e "\n${BLUE}=== Checking ${ORANGE}$dir${RESET}${BLUE} ===${RESET}"
+
+        if [ -d "$dir/.git" ]; then
+            found_repo=true
+            output=$(cd "$dir" && git status -s)
+
+            if [[ -z "$output" ]]; then
+                echo -e "${GREEN}No changes${RESET}"
+            else
+                echo -e "${YELLOW}$output${RESET}"
+            fi
+        else
+            echo -e "${MAGENTA}Not initialized${RESET}"
+        fi
+    done
+
+    if ! $found_repo; then
+        echo -e "${RED}No Git repositories found.${RESET}"
+    fi
+}
+
+# tmux alias
+alias t='tmux'                    
+alias ta='tmux attach -t'
+alias td='tmux detach'         
+alias tl='tmux list-sessions'     
+alias tn='tmux new -s'            
+alias tk='tmux kill-session -t'   
+alias ts='tmux switch -t'         
+alias tks='tmux kill-server'      
+alias trew='tmux rename-window'
+alias tres='tmux rename-sessiont -t'
+alias tw='tmux list-windows'      
+alias tns='tmux new-session -A -s'
+
 
 # Kubernetes Alias
 alias k='kubectl'
@@ -142,24 +196,6 @@ dsk() {
     fi
 }
 
-function lazygit() {
-    if [ -z "$1" ]; then
-        echo "Error: Commit message is required."
-        echo "Usage: lazygit '<commit_message>' <branch_name>"
-        return 1
-    fi
-
-    if [ -z "$2" ]; then
-        echo "Error: Branch name is required"
-        echo "Usage: lazygit '<commit_message>' <branch_name>"
-        return 1
-    fi
-
-    git add -A
-    git commit -m "$1"
-    git push -u origin "$2"
-}
-
 explain() {
     if [ "$#" -eq 0 ]; then
         while read -p "Command: " cmd; do
@@ -175,29 +211,14 @@ explain() {
     fi
 }
 
-gdst() {
-    found_repo=false
-    for dir in */; do
-        echo -e "\n${BLUE}=== Checking ${ORANGE}$dir${RESET}${BLUE} ===${RESET}"
-
-        if [ -d "$dir/.git" ]; then
-            found_repo=true
-            output=$(cd "$dir" && git status -s)
-
-            if [[ -z "$output" ]]; then
-                echo -e "${GREEN}No changes${RESET}"
-            else
-                echo -e "${YELLOW}$output${RESET}"
-            fi
-        else
-            echo -e "${MAGENTA}Not initialized${RESET}"
-        fi
-    done
-
-    if ! $found_repo; then
-        echo -e "${RED}No Git repositories found.${RESET}"
-    fi
+lintsh() {
+  shellcheck "$1"
 }
+
+fmtsh() {
+  shfmt -i 2 -sr -ci -w "$1"
+}
+
 
 epoch() {
     local num=${1:--1}
@@ -292,7 +313,7 @@ vimfo() {
 tmuxfo() {
     echo -e "${BLUE}Tmux Cheatsheet${RESET}\n"
 
-    # Splitting Windows
+    # Splitting Panes
     echo -e "${ORANGE}Splitting Panes:${RESET}"
     echo -e "${MAGENTA}Ctrl b %${RESET} - Split vertically"
     echo -e "${MAGENTA}Ctrl b \"${RESET} - Split horizontally\n"
@@ -302,7 +323,7 @@ tmuxfo() {
     echo -e "${MAGENTA}Ctrl b x${RESET} - Close current pane"
     echo -e "${MAGENTA}Ctrl b !${RESET} - Break pane into new window\n"
 
-    # Navigation
+    # Pane Navigation
     echo -e "${ORANGE}Pane Navigation:${RESET}"
     echo -e "${MAGENTA}Ctrl b h${RESET} - Move to left pane"
     echo -e "${MAGENTA}Ctrl b j${RESET} - Move to lower pane"
@@ -310,7 +331,7 @@ tmuxfo() {
     echo -e "${MAGENTA}Ctrl b l${RESET} - Move to right pane"
     echo -e "${MAGENTA}Ctrl b q${RESET} - Show pane numbers\n"
 
-    # Resizing
+    # Pane Resizing
     echo -e "${ORANGE}Pane Resizing:${RESET}"
     echo -e "${MAGENTA}Ctrl b Alt h${RESET} - Decrease width"
     echo -e "${MAGENTA}Ctrl b Alt l${RESET} - Increase width"
@@ -324,24 +345,37 @@ tmuxfo() {
     echo -e "${MAGENTA}Ctrl b n${RESET} - Next window"
     echo -e "${MAGENTA}Ctrl b p${RESET} - Previous window"
     echo -e "${MAGENTA}Ctrl b w${RESET} - List windows"
-    echo -e "${MAGENTA}Ctrl b ,${RESET} - Rename window"
-    echo -e "${MAGENTA}Ctrl b &${RESET} - Close window\n"
+    echo -e "${MAGENTA}Ctrl b ,${RESET} - Rename current window"
+    echo -e "${MAGENTA}Ctrl b &${RESET} - Close current window\n"
 
-    # Sessions
+    #Sessions
     echo -e "${ORANGE}Sessions:${RESET}"
-    echo -e "${MAGENTA}tmux new -s <mysession>${RESET} - Create a new session"
-    echo -e "${MAGENTA}tmux ls${RESET} - List sessions"
-    echo -e "${MAGENTA}tmux attach -t <mysession>${RESET} - Attach to session"
-    echo -e "${MAGENTA}tmux detach${RESET} - Detach from session"
-    echo -e "${MAGENTA}tmux kill-session -t <mysession>${RESET} - Kill session\n"
+    echo -e "${MAGENTA}tmux new -s <name>${RESET} or ${MAGENTA}tn${RESET} - Create a new session"
+    echo -e "${MAGENTA}tmux detach${RESET} or ${MAGENTA}td${RESET} - Detach from current session"
+    echo -e "${MAGENTA}tmux ls${RESET} or ${MAGENTA}tl${RESET} - List sessions"
+    echo -e "${MAGENTA}tmux attach -t <name>${RESET} or ${MAGENTA}ta${RESET} - Attach to session"
+    echo -e "${MAGENTA}tmux detach${RESET} - Detach from current session"
+    echo -e "${MAGENTA}tmux rename-session -t <old_name> <new_name>${RESET} or ${MAGENTA}tres${RESET} - Rename session" 
+    echo -e "${MAGENTA}tmux kill-session -t <name>${RESET} or ${MAGENTA}tk${RESET} - Kill a session"
+    echo -e "${MAGENTA}tmux switch -t <name>${RESET} or ${MAGENTA}ts${RESET} - Switch to another session\n"
 
-    # Launch Commands
+    # Launching with Splits
     echo -e "${ORANGE}Launch with Splits:${RESET}"
-    echo -e "${MAGENTA}tmux new-session -d -s <mysession>${RESET} - Start a detached session"
-    echo -e "${MAGENTA}tmux split-window -h${RESET} - Create horizontal split"
-    echo -e "${MAGENTA}tmux split-window -v${RESET} - Create vertical split"
-    echo -e "${MAGENTA}tmux select-layout tiled${RESET} - Arrange panes in a tiled layout\n"
+    echo -e "${MAGENTA}tmux new-session -d -s <name>${RESET} - Start a detached session"
+    echo -e "${MAGENTA}tmux new-session -A -s <name>${RESET} or ${MAGENTA}tns${RESET} - Create if not exists, or attach"
+    echo -e "${MAGENTA}tmux split-window -h${RESET} - Split horizontally"
+    echo -e "${MAGENTA}tmux split-window -v${RESET} - Split vertically"
+    echo -e "${MAGENTA}tmux select-layout tiled${RESET} - Tile all panes"
+    echo -e "${MAGENTA}tmux kill-server${RESET} or ${MAGENTA}tks${RESET} - Kill the tmux server\n"
+
+    # Copy Mode
+    echo -e "${ORANGE}Copying:${RESET}"
+    echo -e "Use ${MAGENTA}Shift + mouse drag${RESET} to highlight and copy from the terminal"
+    echo -e "Use ${MAGENTA}Ctrl b [${RESET} to enter copy mode (if mouse isn't working), to exit press ${MAGENTA}q${RESET}"
+    echo -e "Then ${MAGENTA}Space${RESET} to start selection, and ${MAGENTA}Enter${RESET} to copy"
+    echo -e "Paste with ${MAGENTA}Ctrl b ]${RESET}\n"
 }
+
 
 vscfoo() {
     ## FILL shortcuts and tips for VS Code
@@ -430,8 +464,9 @@ show_kubernetes_commands() {
 }
 
 show_utility_commands() {
-    echo -e "${ORANGE}List of Terminal Utility functions:${RESET}"
+    echo -e "${ORANGE}List of Terminal Utility alias and functions:${RESET}"
     echo -e "${MAGENTA}ll${RESET} - Long list."
+    echo -e "${MAGENTA}v${RESET} - vim"
     echo -e "${MAGENTA}aqui${RESET} - Open the current directory in Windows Explorer (WSL Only)."
     echo -e "${MAGENTA}fmedia${RESET} - Move all .mkv and .mp4 files to the current directory."
     echo -e "${MAGENTA}cdd${RESET} - Change directory to Windows Desktop on WSL (WSL Only)."
@@ -451,6 +486,8 @@ show_utility_commands() {
     echo -e "${MAGENTA}ippubf${RESET} - Show information on ISP and Public IP"
     echo -e "${MAGENTA}field${RESET} - Extract specific fields from a line. Usage: ${YELLOW}field <column_number> <delimiter>${RESET}"
     echo -e "${MAGENTA}epoch${RESET} - Convert epoch to human-readable date. Usage: ${YELLOW}epoch <epoch_time>${RESET}"
+    echo -e "${MAGENTA}lintsh${RESET} - Lint shell scripts using ShellCheck. Usage: ${YELLOW}lintsh <file.sh>${RESET}"
+    echo -e "${MAGENTA}fmtsh${RESET} - Format shell scripts using shfmt. Usage: ${YELLOW}fmtsh <file.sh>${RESET}"
     echo -e "${MAGENTA}rb${RESET} - Reload \$HOME/.bashrc"
     echo -e "${MAGENTA}eb${RESET} - Open \$HOME/.bashrc in vim"
     echo -e "${MAGENTA}ebt${RESET} - Open \$HOME/.bash_tools in vim"
@@ -464,6 +501,7 @@ show_utility_commands() {
     echo -e "${MAGENTA}tmuxfo${RESET} - Show custom tmux keymaps and cheatsheet"
     echo -e "${MAGENTA}vscfoo${RESET} - Show Visual Studio Code keymaps and cheatsheet"
     echo -e "${MAGENTA}svim${RESET} - Edit files with sudo. Equal to 'sudoedit' and 'sudo -e'"
+    echo -e "${MAGENTA}colors${RESET} - Print all 256 colors in the terminal."
 }
 
 show_media_commands() {
@@ -480,11 +518,14 @@ show_media_commands() {
     echo -e "${MAGENTA}getalb${RESET} - Download an album from Spotify and save it in desktop. Usage: ${YELLOW}getalb <url>${RESET}"
 }
 
-show_custom_commands() {
+show_starship_commands() {
     echo -e "${ORANGE}List of Customization functions:${RESET}"
-    echo -e "${MAGENTA}set_prompt_colors${RESET} - Change theme of Terminal/Prompt 0-29. Usage: ${YELLOW}set_prompt_colors <number 0-29>${RESET}"
-    echo -e "${MAGENTA}colors${RESET} - Print all 256 colors in the terminal."
+    echo -e "${MAGENTA}pcolor${RESET} - Change theme of Prompt 0-29. Usage: ${YELLOW}pcolor <theme-name>${RESET}"
+    echo -e "${MAGENTA}starship explain${RESET} - Explain current Starship prompt configuration."
+
 }
+    
+
 
 show_help() {
     echo -e "${YELLOW}Available sections:${RESET}"
@@ -492,7 +533,7 @@ show_help() {
     echo "- kubernetes     (or k8s - Kubernetes commands)"
     echo "- utils          (or utilities, terminal - Terminal utilities)"
     echo "- youtube        (or yt, spotify, media - Media download commands)"
-    echo "- custom         (or customization, misc - Customization commands)"
+    echo "- starship       (or theme, skin - Starship prompt customization)"
     echo "- all            (Show all commands)"
 }
 
@@ -501,20 +542,20 @@ lscom() {
     local section="${1:-all}"
 
     case "$section" in
-    "git" | "Git")
+    "git")
         show_git_commands
         ;;
-    "k8s" | "kubernetes" | "Kubernetes")
+    "k8s" | "kubernetes")
         show_kubernetes_commands
         ;;
-    "utils" | "utilities" | "terminal")
+    "utils" | "utilities" | "terminal" | "utility" | "cli")
         show_utility_commands
         ;;
     "youtube" | "yt" | "spotify" | "media")
         show_media_commands
         ;;
-    "custom" | "customization" | "misc" | "theme" | "skin")
-        show_custom_commands
+    "starship" | "Starship" | "prompt" | "ps1" | "custom" | "customization" | "misc" | "theme" | "skin")
+        show_starship_commands
         ;;
     "all" | "")
         show_git_commands
@@ -525,7 +566,7 @@ lscom() {
         echo
         show_media_commands
         echo
-        show_custom_commands
+        show_starship_commands
         ;;
     *)
         show_help
